### ISSUE TITLE
Úkol 1

### ISSUE THREAD

**Issue by jotkac** [jotkac/python2022#1]
https://github.com/jotkac/python2022/blob/main/test.py

Odevzdávám první úkol – teda doufám :)

**Comment by AnetaPopelova** [comment]
Ahoj :-) 

Prvni cast jsi zvladla skvele, naucit se s gitem 👍

V souboru test.py ale vidim jen zkusebni 
`print("Ahoj!")`

Zadani prvniho ukolu najdes tady: https://github.com/lutydlitatova/python-jaro-2022/blob/main/ukoly/ukol-01.md

**Comment by jotkac** [comment]
Aha, nějak jsem z toho byla zblblá a ten úkol jsem přehlídla. Posílám tedy znovu, snad tentokrát líp :) 

https://github.com/jotkac/python2022/blob/main/ukol1.py

**Comment by AnetaPopelova** [comment]
Super!
